### ISSUE TITLE
Task 6 (property search card)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#4]
In the starter html file(located in  /tasks/task-006/card.html) there is the design for a card showing summary of a property. There are some changes/additions have to be made.

###Add MLS and brokerage info
First, there are two more pieces of information to be added:
- MLS number, which is a text like "MLS® #: R2586154"
- The brokerage name, something like "Nu Stream Realty Inc."

Now you have to insert these texts somewhere in the card. Teh details are up to you, but some suggestions:

- You may insert some info within the image (include them as div inside the .ss-prop-card__img div and make them position:absolute). For example, the mls number can go on the top-left corner of the image with some half-transparent background.
- I recommend to not to add to the "content" part of the card, but rather try to squeex these in the image area (like one on the top-left, and the other on the bottom center). But I'm open to any other creative idea that looks nice. feel free to rearrange things. The goal is to have a minimal card with all the helpful information

Please note that the main class for this card (ss-prop-card) is located in the folder /project-cmps/_prop-cards.scss (feel free to modify this file). Follow BEM guideline.

###Map link
Notice there is a map link right after the address. 
- Make it a bit bigger, include a map icon/svg/image with it so that it makes mor esense.
- What is the address is too long? So change the layout (using d-flex align-items-center) to 
 - show the address and map link side by side,
 - show the map link on the right side
 - show "docts" in the address if the address is to long (use the mixin "dot-text-overflow" in styles/_mixins.scss)

Test your design by writing a long address.

###Focus outline
Note that there appears a red border around the card when you click on it. This is because of the :focus style. Make this style more advanced, maybe try adding a pulsing red shadow as described https://codepen.io/olam/pen/zcqea

Learn more: Why did I use tabindex for the ss-prop-card? Remove the tab index and see what change it makes

Learn more: The link in the code pen uses "CSS animation" This is a great topic and we are going to use css animation a lot. You may familiarize yourself with it (quite easy)

**Comment by pmvald** [comment]
@YusukeYoshihiro Once you are done with the previous task writeup, please move on to this task. It is a more serious task.

**Comment by YusukeYoshihiro** [comment]
Task 6 done
###Add MLS and brokerage info
First, there are two more pieces of information to be added:

- You may insert some info within the image (include them as div inside the .ss-prop-card__img div and make them position:absolute). For example, the mls number can go on the top-left corner of the image with some half-transparent background. 
`-> I added "MLS number as "MLS® #: R2586154" on the top-left of the image by using "position: absolute".` 

- I recommend to not to add to the "content" part of the card, but rather try to squeex these in the image area (like one on the top-left, and the other on the bottom center). But I'm open to any other creative idea that looks nice. feel free to rearrange things. The goal is to have a minimal card with all the helpful information
`-> I added to try to rearenge "The brokerage name" as "Nu Stream Realty Inc." on the bottom-right of the img by using "position: absolute".` 

Please note that the main class for this card (ss-prop-card) is located in the folder /project-cmps/_prop-cards.scss (feel free to modify this file). Follow BEM guideline.

###Map link
Notice there is a map link right after the address. 
- Make it a bit bigger, include a map icon/svg/image with it so that it makes mor sense. 
 `->I added the "map icon" from Bootstrap with <link> and  I made it bigger the map and the icon.`
- What is the address is too long? So change the layout (using d-flex align-items-center) to 
 - show the address and map link side by side, `-> done`
 - show the map link on the right side`->done`
 - show "docts" in the address if the address is to long (use the mixin "dot-text-overflow" in styles/_mixins.scss)
 `->done`

Test your design by writing a long address.`-> done by using Lorem ipsum`

###Focus outline
Note that there appears a red border around the card when you click on it. This is because of the :focus style. Make this style more advanced, maybe try adding a pulsing red shadow as described https://codepen.io/olam/pen/zcqea

Learn more: Why did I use tabindex for the ss-prop-card? Remove the tab index and see what change it makes
`-> Fist of all , " tabindex"  attribute is possible to make elements ,which are originally not able to "focus" , enable for using ":focus" on CSS . Also, in this case, we used 'tabindex="0"', which means it possible to focus and set orders how appear the element in order, and we can see it by click or pushing Tab key like 1 → 2 → 3 → （0 or element of enable to focus）.`
Learn more: The link in the code pen uses "CSS animation" This is a great topic and we are going to use css animation a lot. You may familiarize yourself with it (quite easy)
`->done`

**Comment by YusukeYoshihiro** [comment]
@pmvald Thank you for giving me lectures and review my Code. 
Then, if you need help to complete more Tasks, please make me do the task.
Thanks
